### PR TITLE
Correct a typo in updateUserInformation

### PR DESCRIPTION
**Pull request by trohovsky**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @trohovsky, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by trohovsky** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @trohovsky has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by trohovsky** [comment]
Any chance it will be merged?

**Comment by gcurtis** [comment]
Hey @trohovsky, thanks for your contribution, but unfortunately changing a public method name would result in a backwards-compatible change. This version of the SDK is also deprecated, so we're not accepting any non-critical fixes.

Please feel free to contribute to the new version of the SDK at https://github.com/box/box-java-sdk.

**Pull request closed without merging**
